ui <- navbarPage(title = "CA Community Burden of Disease Engine",
                 id = "navsID",
                 # position = "fixed-top",
                 theme = "style.css", 
                 tabPanel(title = strong("HOME"), value = "home"), 
                 tabPanel(title = strong("MAPS"), value = "maps", 
                          tabsetPanel(type = "tab", id = "mapsID", 
                                      tabPanel(title = "INTERACTIVE MAP", value = "interactiveMapTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("RANKS"), value = "ranks", 
                          tabsetPanel(type = "tab", id = "ranksID", 
                                      tabPanel(title = "RANK BY CAUSE - Deaths", value = "rankByCauseTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())), 
                                      tabPanel(title = "RANK BY GEOGRAPHY - Deaths", value = "rankByCauseTab",
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "AGE RACE FOCUS", value = "ageRaceFocusTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "Death Hosp ED", value = "deathHospEDTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "Attributable Risks - IHME", value = "riskByCauseTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "Two-Year IHME Rankings", value = "arrowsTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("TRENDS"), value = "trends",
                          tabsetPanel(id = "trendsID", 
                                      trendSex_ui(id = "sexTrendTab"),
                                      tabPanel(title = "Age Trend", value = "ageTrendTab", 
                                               sidebarLayout(sidebarPanel_custom(tabID = "sexTrendTab"), 
                                                             mainPanel())),
                                      tabPanel(title = "Race Trend", value = "raceTrendTab", 
                                               sidebarLayout(sidebarPanel_custom(tabID = "sexTrendTab"), 
                                                             mainPanel())),
                                      tabPanel(title = "Education Trend", value = "educationTrendTab", 
                                               sidebarLayout(sidebarPanel_custom(tabID = "sexTrendTab"), 
                                                             mainPanel())),
                                      tabPanel(title = "Life Expectancy", value = "lifeExpectancyTab", 
                                               sidebarLayout(sidebarPanel_custom(tabID = "sexTrendTab"), 
                                                             mainPanel())),
                                      tabPanel(title = "Leading Causes", value = "topTrendsTab", 
                                               sidebarLayout(sidebarPanel_custom(tabID = "sexTrendTab"), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("DISPARITIES"), value = "disparities", 
                          tabsetPanel(type = "tab", id = "disparitiesID", 
                                      tabPanel(title = "Disparities", value = "disparitiesTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("SDOH"), value = "sdoh", 
                          tabsetPanel(type = "tab", id = "sdohID", 
                                      tabPanel(title = "SOCIAL DETERMINANTS", value = "sdohTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("HOSPITALIZATIONS"), value = "hospitalizations", 
                          tabsetPanel(type = "tab", id = "hospitalizationsID", 
                                      tabPanel(title = "HOSPITAL DISCHARGE", value = "hospitalDischargeTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "HOSPITAL DISCHARGE--PRIMARY AND ANY DIAGNOSES", value = "hospitalPrimaryAnyTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong("DEMOGRAPHICS"), value = "demographics", 
                          tabsetPanel(type = "tab", id = "demographicsID", 
                                      tabPanel(title = "Demographics", value = "demographicsTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      )), 
                 tabPanel(title = strong(" DATA TABLE"), value = "dataTableTab"), 
                 tabPanel(title = strong("ABOUT"), value = "about", 
                          tabsetPanel(type = "tab", id = "aboutID", 
                                      tabPanel(title = "OVERVIEW", value = "overviewTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "Technical Documentation", value = "techDocTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "Links to Other Data", value = "otherLinksTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel())),
                                      tabPanel(title = "CCB URL Parameters", value = "urlParametersTab", 
                                               sidebarLayout(sidebarPanel_custom(), 
                                                             mainPanel()))
                                      ))
                 ) # END OF NAVBARPAGE



